spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
    use-code-as-default-message: true
resilience4j.circuitbreaker:
    instances:
        empresaService:
            registerHealthIndicator: true
            ringBufferSizeInClosedState: 5
            ringBufferSizeInHalfOpenState: 3
            waitDurationInOpenState: 10s
            failureRateThreshold: 50
            recordExceptions:
                - java.util.concurrent.TimeoutException
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka
            
